# Generated by Django 2.2.3 on 2019-07-30 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_create_app_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='count',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Staff units count'),
        ),
    ]
