# Generated by Django 2.2.3 on 2019-07-30 10:26

import core.validators
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_create_app_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(validators=[core.validators.validate_monday], verbose_name='Start')),
                ('end', models.DateField(validators=[core.validators.validate_sunday], verbose_name='End')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='employee.Employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, help_text='A label for URL config.', max_length=128, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), "Enter a valid 'slug' consisting of Unicode letters, numbers, underscores, or hyphens.", 'invalid'), core.validators.validate_slug])),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveSmallIntegerField(validators=[core.validators.validate_positive, django.core.validators.MaxValueValidator(168)], verbose_name='Hours')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projectassignments', to='schedule.Assignment', verbose_name='Assignment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projectassignments', to='schedule.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Project assignment',
                'verbose_name_plural': 'Project assignments',
                'unique_together': {('assignment', 'project')},
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='projects',
            field=models.ManyToManyField(related_name='assignments', through='schedule.ProjectAssignment', to='schedule.Project', verbose_name='Projects'),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Start')),
                ('end', models.DateField(verbose_name='End')),
                ('hours', models.PositiveSmallIntegerField(validators=[core.validators.validate_positive], verbose_name='Hours')),
                ('reason', models.TextField(blank=True, help_text='Reason for employee absence', verbose_name='Reason')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='absences', to='employee.Employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee absence',
                'verbose_name_plural': 'Employee absences',
                'ordering': ['-start'],
            },
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(check=models.Q(start__exact=django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('end'), '-', django.db.models.expressions.DurationValue(datetime.timedelta(days=6), output_field=models.DurationField()))), name='correct_employee_assignment_week_range'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('employee', 'start', 'end')},
        ),
        migrations.AddConstraint(
            model_name='absence',
            constraint=models.CheckConstraint(check=models.Q(start__lte=django.db.models.expressions.F('end')), name='correct_employee_absence_range'),
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together={('employee', 'start', 'end')},
        ),
    ]
