# Generated by Django 2.2.3 on 2019-07-30 19:00

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_create_app_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absence',
            options={'ordering': ['-start'], 'verbose_name': "Employee's absence", 'verbose_name_plural': "Employees' absences"},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-start'], 'verbose_name': "Employee's assignments", 'verbose_name_plural': "Employees' assignments"},
        ),
        migrations.AlterModelOptions(
            name='projectassignment',
            options={'verbose_name': "Project's assigment", 'verbose_name_plural': "Projects' assigments"},
        ),
        migrations.RemoveConstraint(
            model_name='assignment',
            name='correct_employee_assignment_week_range',
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(check=models.Q(start__exact=django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('end'), '-', django.db.models.expressions.DurationValue(datetime.timedelta(days=6), output_field=models.DurationField()))), name='correct_assignment_week_range'),
        ),
    ]
