# Generated by Django 2.2.3 on 2019-08-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_change_models_vebose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectassignment',
            options={'ordering': ['-assignment__start'], 'verbose_name': "Project's assigment", 'verbose_name_plural': "Projects' assigments"},
        ),
    ]
