# Generated by Django 2.2.4 on 2019-08-11 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_change_assignments_from_employee_to_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='employment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='employee.Employment', verbose_name='Position held'),
        ),
    ]
