# Generated by Django 2.2.4 on 2019-08-11 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_change_assignment_employment_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='employment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='employee.Employment', verbose_name='Position'),
        ),
    ]
