# Generated by Django 2.2.3 on 2019-07-26 03:58

import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, help_text='A label for URL config.', max_length=128, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), "Enter a valid 'slug' consisting of Unicode letters, numbers, underscores, or hyphens.", 'invalid'), core.validators.validate_slug])),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(allow_unicode=True, editable=False, help_text='A label for URL config.', max_length=128, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), "Enter a valid 'slug' consisting of Unicode letters, numbers, underscores, or hyphens.", 'invalid'), core.validators.validate_slug])),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Staffing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Staff Units')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staffing', to='staffing.Department', verbose_name='Department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staffing', to='staffing.Position', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Staff Unit',
                'verbose_name_plural': 'Staff Units',
                'ordering': ['department__name', 'position__name'],
                'unique_together': {('department', 'position')},
            },
        ),
        migrations.AddField(
            model_name='department',
            name='positions',
            field=models.ManyToManyField(related_name='departments', through='staffing.Staffing', to='staffing.Position', verbose_name='Positions'),
        ),
    ]
