# Generated by Django 2.2.3 on 2019-07-27 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0001_create_app_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffing',
            options={'ordering': ['department__name', 'position__name'], 'verbose_name': 'Staff unit', 'verbose_name_plural': 'Staff units'},
        ),
        migrations.AlterField(
            model_name='staffing',
            name='count',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Staff unit count'),
        ),
    ]
