# Generated by Django 2.2.4 on 2019-08-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0003_change_count_verbose_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffing',
            options={'ordering': ['position__name', 'department__name'], 'verbose_name': 'Staff unit', 'verbose_name_plural': 'Staff units'},
        ),
    ]
